### ISSUE TITLE
Autores

### ISSUE THREAD

**Issue by rociojoo** [LatinR/latinr#4]
Hola Elio,
cuando hago un knit del .Rmd siempre obtengo un pdf con autores anónimos. ¿Alguna idea de qué pueda estar pasando y cómo arreglarlo?
Gracias,
Rocío

**Comment by rociojoo** [comment]
¿O es a propósito para hacer selección de resúmenes a ciegas? Acabo de leer mejor el readme. Es eso. Cierro el issue!

**Comment by eliocamp** [comment]
Hola! 
Sí, por default va en anónimo. Para ver cómo queda el documento usando tu nombre (te van a pedir el trabajo es aceptado) tenés que modificar el yaml y poner:

```yaml
output: 
    latinr::latinr_article:
      submission: false    # <- este es el cambio
```
